### ISSUE TITLE
IOS APP Source code 

### ISSUE THREAD

**Issue by blackfa1con** [usbarmory/armory-drive#5]
I bought the usb armory for my project, I can’t find the sources for the ios app or at least an example code to integrate it into my own files 
( Ex: C++ JNI code or java ) to lock/unlock the usb armory drive via BLE.
Where i can find the ios app source or is there any tutorial show us how to unlock the drive from java code or c under android os ?

**Comment by abarisani** [comment]
The iOS app is not Open Source, however the armory-drive firmware repository includes the API that a client would need to implement (see protobuf specifications and server side Go code).

**Comment by blackfa1con** [comment]
Ok, I understand the API  … 
but as shown on page (4) from this brochure :
( https://eu.mouser.com/pdfDocs/f-secure-usb-armory-brochure.pdf ) 

“ BESPOKE TRANSPARENCY
The USB armory has been developed entirely in-house by F-Secure Foundry and is manufactured in Italy.
**The schematics and layout are open to the public as well as its core software, drivers and tools.**
This gives unparalleled transparency to all customers “

This mean for me when I ordered this product i thought that the project is fully open source, so i can rebuild it to suit my project.
But NOW i see that a part of this project still closed source!, Please guy’s update the documentation or tell the customers that you need to build your own app from scratch for IOS or Android or any other OS if you want to customize this open source HW/SW by yourself.
If i know that the app which controlling the armory drive over BLE is not open source before i ordered,absolutely i WONT take this semi open source hardware to integrate into our project.

**Comment by abarisani** [comment]
That sentence refers to the USB armory and its base environment. Armory Drive is just one specific application (developed much later than the release of the USB armory) and the closed source part is the one running outside the USB armory itself. All code running on the USB armory for which we publish binaries for is open, therefore we don't see our documentation as inaccurate.
